### ISSUE TITLE
Add pass to list of KEYS

### ISSUE THREAD

**Issue by nidkil** [watson/is-secret#3]
Hi,

Cool module. I'm using it in conjunction with redact-secrets.

The key 'pass' (`/^pass$/`) is missing from the KEYS. Can you please add it?

**Comment by watson** [comment]
This have been added to the latest release

**Comment by nidkil** [comment]
Thx for the quick action!

**Comment by nidkil** [comment]
Has redact-secrets also been updated to use the latest version?

**Comment by watson** [comment]
It depends on `^1.0.0`, so if you reinstall, it will use the new version

**Comment by nidkil** [comment]
Got it. Thx.
